$(document).ready(function(){
    $("#finder").val('frm1');
    $("#frm1_submit").click(function(event){
        event.preventDefault();
        pagenav(1);
    });
    $("#frm1_reset").click(function(event){
        event.preventDefault();
        $('#frm1')[0].reset();
        pagenav(1);
    });
});